# Generated by Django 4.2.3 on 2023-08-10 07:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('condition', models.CharField(choices=[('USEABLE', 'Useable'), ('USED', 'Used'), ('SCRAP', 'Scrap'), ('RERAIRABLE', 'Repairable')], max_length=100)),
                ('Price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=100)),
                ('lots', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auction.lot')),
            ],
        ),
    ]
