# Generated by Django 4.2.3 on 2023-08-14 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_remove_auction_lots_lot_auction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot',
            name='auction',
        ),
        migrations.AddField(
            model_name='auction',
            name='lots',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auction.lot'),
        ),
    ]
