# Generated by Django 4.2.3 on 2023-08-16 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_auction_subscribed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='subscribed',
        ),
    ]
