# Generated by Django 4.2.3 on 2023-08-16 11:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auction', '0008_alter_auction_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='subscribers',
            field=models.ManyToManyField(blank=True, default=None, to=settings.AUTH_USER_MODEL),
        ),
    ]
