# Generated by Django 4.2.3 on 2023-08-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0010_auction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PREPARING', 'Preparing')], default='PREPARING', max_length=50),
        ),
    ]
